### ISSUE TITLE
Health centers import proposal

### ISSUE THREAD

**Issue by karitotp** [osm-pe/health-centers-import#1]
## Open data

There are available data of health centers of Peru in https://www.datosabiertos.gob.pe/dataset/minsa-ipress/resource/7cf96151-5ddf-4281-90ba-b2b0407447ab#{}, the source is the SUSALUD - Superintendencia Nacional de Salud as mention in the portal. 

The format file is CSV which contains 20,819 health centers of which 7,933 have coordinates so we can add them to OSM and improve the map, especially in the rural areas where this type of info is poor.

### Dataset that could be imported

The data of this **7,933** health centers with coordinates was uploaded to this repo in geojson and csv format.

**Attributes of a point**

- categoria
- clasificacion
- codigo
- codigo_DISA
- codigo_microred
- codigo_red
- departamento
- direccion
- distrito
- horario
- institución
- nombre_establecimiento
- provincia
- telefono
- tipo
- ubigeo

---

Thoughts and comments about this proposal of importation are welcome.

**Comment by karitotp** [comment]
A fin de determinar los atributos que podemos utilizar para subir los datos a OSM, aquí más detalle de los datos que cada centro de salud tiene.

- **Código**
- **Nombre de establecimiento**
- **Tipo de establecimiento**: Pueden ser;
  - Establecimiento de Salud sin internamiento
  - Establecimiento de Salud con internamiento
  - Servicio Médico de Apoyo 
- **Clasificación**: Depende del tipo de establecimiento;
  - Establecimiento de Salud sin internamiento:
    - PUESTOS DE SALUD O POSTAS DE SALUD
    - CENTROS DE SALUD O CENTROS MEDICOS
    - POLICLINICOS
    - CENTROS MEDICOS ESPECIALIZADOS
    - CONSULTORIOS MEDICOS Y DE OTROS PROFESIONALES DE LA SALUD
  - Establecimiento de Salud con internamiento:
    - HOSPITALES O CLINICAS DE ATENCION GENERAL
    - HOSPITALES O CLINICAS DE ATENCION ESPECIALIZADA
    - CENTROS DE SALUD CON CAMAS DE INTERNAMIENTO
    - CENTROS DE ATENCION GERIATRICA
    - INSTITUTOS DE SALUD ESPECIALIZADOS
   - Servicio Médico de Apoyo:
     - PATOLOGIA CLINICA
     - ANATOMIA PATOLOGICA
     - DIAGNOSTICO POR IMAGENES
     - MEDICINA NUCLEAR
     - RADIOTERAPIA
     - MEDICINA FISICA
     - REHABILITACION
     - HEMODIALISIS
     - LITOTRIPSIA
     - MEDICINA HIPERBARICA
     - ENDOSCOPIAS
     - COLPOSCOPIAS
     - SERVICIO DE TRASLADO DE PACIENTES, ATENCION DOMICILIARIA O ATENCION PREOSPITALARIA
     - ESTABLECIMIENTOS DE RECUPERACION O REPOSO
     - CENTROS OPTICOS
     - LABORATORIOS DE PROTESIS DENTAL
     - ORTOPEDIAS Y SERVICIOS DE PODOLOGIA
     - CENTROS DE ATENCION PARA DEPENDIENTES A SUSTANCIAS PSICOACTIVAS Y OTRAS DEPENDENCIAS
     - CENTROS DE VACUNACION
     - CENTROS DE MEDICINA ALTERNATIVA 
- **Institución**: Intitución a la que pertenece, pueden ser;
   - Minsa
   - Essalud
   - Sanidad del Ejécito
   - Sanidad de la Fuerza Aérea
   - Sanidad de la Policía Nacional del Perú
   - Sanidad Naval
   - Gobierno Regional
   - Gobierno Provincial
   - Privado
   - Otro
- **Departamento**
- **Provincia**
- **Distrito**
- **Ubigeo**
- **Dirección**
- **Código DISA**: Código de dirección de Salud
-  **Código Red**: Código de Red de establecimiento
- **Código Microred**: Código de Microred de establecimiento
- **Categoría**: Pueden ser;
   - 0 (Sin categoría)
   - I-1
   - I-2
   - I-3
  - I-4
  - II-1
  - II-2
  - III-1
  - III-2
- **Teléfono**
- **Horario de atención**

### Etiquetas que podemos utilizar para :world_map: 

| **Datos**          | Etiqueta OSM  | Agregar/Ignorar |
| ----------------- | -------- | ---------- |
| Código |       | Ignorar         |
| Nombre de establecimiento | name      |      Agregar    |
| Tipo de establecimiento | type      |     Agregar     |
| Clasificación |  classification     |       Agregar   |
| Institución |    institution   |    Agregar      |
| Departamento |       |      Ignorar    |
| Provincia |       |     Ignorar     |
| Distrito |       |       Ignorar   |
| Ubigeo |       |     Ignorar     |
| Dirección |    adreess   |     Agregar  (opcional)   |
| Código DISA |       |   Ignorar       |
| Código Red |  codigo_red     |      Agregar    |
| Código Microred |    codigo_microred   |    Agregar      |
| Categoría |    category   |     Agregar     |
| Teléfono|    phone   |      Agregar   (opcional) |
| Horario de atención|   opening_hours    |      Agregar   (opcional)    |

_No todos los centros de salud a importar tienen los datos de `Dirección`, `Teléfono` u `Horario de atención`, por lo que estas etiquetas se agregarán sólo en caso de que esten claras_

Para poder agregar la etiqueta de `amenity=*` podemos tomar de refecrencia la `Clasificación` :point_up_2: .

**Comment by ovruni** [comment]
Hola Karito

Agrego algunas ideas sobre el etiquetado en base a la propuesta:

- Utilizar [operator](https://wiki.openstreetmap.org/wiki/Key:operator) en lugar de "institution". También se podrían utilizar [operator:type](https://wiki.openstreetmap.org/wiki/Key%3Aoperator%3Atype) en caso sea necesario definir si es privado o público.
- Utilizar [healthcare](https://wiki.openstreetmap.org/wiki/Key%3Ahealthcare) en caso sean necesarios detallar en algunos servicios medicos de apoyo.
- Utilizar [ref](https://wiki.openstreetmap.org/wiki/Key%3Aref) colocar algún codigo o categoría, Algo como "ref:minsa:xx".
- Utilizar [amenity=hospital](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dhospital) para hospitales, [amenity=clinic](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dclinic) para los centros de salud o policlinicos, y [amenity=doctors](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Ddoctors) para algunos de los casos de puestos de salud pequeños (que pueden tener menos de 10 miembros en su personal) o consultorios médicos.

Con lo anterior considero que el uso de type y classification podrían reemplazarse para cada caso, con las etiquetas de clave amenity, healthcare y healthcare:speciality. 

Saludos

**Comment by karitotp** [comment]
Gracias por la sugerencia @ovruni :+1:  

Tomando en cuenta ello las etiquetas a agregar serían:

| **Datos**          | Etiqueta OSM  | Agregar/Ignorar |
| ----------------- | -------- | ---------- |
| Nombre de establecimiento | name = *      |      Agregar    |
| Clasificación |  amenity = hospital <br> amenity = clinic <br> healthcare = *  |       Agregar   |
| Institución |    operator = *    |    Agregar    |
| Dirección |    addr:street = * <br>  addr:full = *  |     Agregar  (opcional)   |
| Código Red | ref:red = *     |      Agregar    |
| Código Microred |    ref:microred = *   |    Agregar      |
| Categoría |    ref:category = *   |     Agregar     |
| Teléfono|    phone = *   |      Agregar   (opcional) |
| Horario de atención|   opening_hours = *    |      Agregar   (opcional)    |

El [wiki](https://wiki.openstreetmap.org/wiki/Health_centers_import_in_Peru) también será actualizado con estos cambios.

**Comment by ovruni** [comment]
Hola Karito

Para el caso de direcciones en OSM existe la clave [addr](https://wiki.openstreetmap.org/wiki/Key:addr) En caso de tener una dirección con manzanas, lotes, etc. se podría usar la clave "addr:full".
Para el caso de números de [telefóno](https://wiki.openstreetmap.org/wiki/Key:phone) sería bueno colocar el número en formato ITU, por ejemplo, un número fijo de Ayacucho sería algo como "+51 66 XXXXXX", mientras que para un número celular solo es necesario algo como "+51 XXXXXXXXX". De esta forma se puede llamar desde cualquier parte del mundo.

Saludos

**Comment by ovruni** [comment]
Hola Karito

He modificado algunos establecimientos de salud, por los siguientes motivos:

- Algunos tenían las etiquetas con la anterior propuesta (tal como adreess, codigo_red, etc).
- Algunos tenían nombres y direcciones con el conector ("Y"), las preposiciones ("De", "Del) o los artículos (El, La, Los, Las) en mayúsculas dentro del texto (en el caso de artículos, solo he cambiado algunos). Este problema todavia se mantiene con la importación de los centros educativos.
- Algunos valores de telefono todavia no contaban con el código de teléfono.
- Algunos valores de la clave "operator" decían "Privado", he cambiado la etiqueta a "operator:type=private".
- Algunos estaban con la clave "ref:microrred" en lugar de "ref:microred".
- Algunos valores de la clave "addr:full" que tenían solo valor de calle las he cambiado a la clave "addr:street" y en algunos casos que contaban con número de puerta los he separado a "addr:housenumber".
- Tambien he cambiado el valor de amenity que estaba con "hospital" para la gran mayoría. Tal como se indica en [amenity=clinic](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dclinic) el uso de "hospital" es para establecimientos grandes. De la misma forma "amenity=doctors" puede usarse para pequeños establecimientos, como suelen ser la mayoria de los que son de "ref:category=I-1", que sobre todo en zonas rurales suele contar con menos de 10 empleados. Para centros de salud se pueden usar "amenity=clinic" como lo suelen ser los de "ref:category:I-3".

Saludos

**Comment by karitotp** [comment]
Gracias Omar! tengo algunas dudas en algunos casos.


> - Algunos tenían las etiquetas con la anterior propuesta (tal como adreess, codigo_red, etc).

Sí, estos fueron los primeros puntos que se importaron. Estas etiquetas ya se corrigieron para los siguientes.

> - Algunos tenían nombres y direcciones con el conector ("Y"), las preposiciones ("De", "Del) o los artículos (El, La, Los, Las) en mayúsculas dentro del texto (en el caso de artículos, solo he cambiado algunos). Este problema todavia se mantiene con la importación de los centros educativos.

Ok, se tendrá más cuidado en estos casos. 

> - Algunos valores de telefono todavia no contaban con el código de teléfono.

Sí, también son los primeros importados. Hay algunos que inician con `#` 0 `*`, por ejemplo: `#0023744` o `*6928252`, en estos casos también se tendría que agregar el código?

> - Algunos valores de la clave "operator" decían "Privado", he cambiado la etiqueta a "operator:type=private".

:+1:, en caso de que `institución` esté como privado se utilizará `operator:type=private`.

> - Algunos estaban con la clave "ref:microrred" en lugar de "ref:microred".

:+1:, los corregiré.

> - Algunos valores de la clave "addr:full" que tenían solo valor de calle las he cambiado a la clave "addr:street" y en algunos casos que contaban con número de puerta los he separado a "addr:housenumber".

:+1: 
Hay casos en los que la dirección es; `Otros Comunidad Nativa Wayampiak S/N`, `Otros Tutumberos S/N` o `Localidad De Huarca` donde no se menciona nombre de calle, etc. En estos casos se debería agregar u omitir? en caso de agregar cuál sería la etiqueta a usar?

> - Tambien he cambiado el valor de amenity que estaba con "hospital" para la gran mayoría. Tal como se indica en [amenity=clinic](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dclinic) el uso de "hospital" es para establecimientos grandes. De la misma forma "amenity=doctors" puede usarse para pequeños establecimientos, como suelen ser la mayoria de los que son de "ref:category=I-1", que sobre todo en zonas rurales suele contar con menos de 10 empleados. Para centros de salud se pueden usar "amenity=clinic" como lo suelen ser los de "ref:category:I-3".

Ok, con esta aclaración las etiquetas a usar serían:
amenity=doctors; para establecimientos pequeños con ref:category=I-1.
amenity=clinic; para establecimientos medianos con ref:category=I-3.
amenity=hospital; para establecimientos grandes 
Es esto correcto?

**Comment by ovruni** [comment]
> > * Algunos valores de telefono todavia no contaban con el código de teléfono.
> 
> Sí, también son los primeros importados. Hay algunos que inician con `#` 0 `*`, por ejemplo: `#0023744` o `*6928252`, en estos casos también se tendría que agregar el código?

Eso podría tratarse de algún número usado de manera privada por alguna operadora (RPM, RPC). En caso sea algún número que solo funciona en Perú, se puede utilizar la clave "phone:PE". Creo que las redes privadas utilizaban * y # anteriormente (incluso un mismo teléfono celular en redes privadas tenia un número corto diferente). También podría ser que se trate de algún error al ingresar el número. Puede que sea mejor dejarlo como "phone:PE".

> Hay casos en los que la dirección es; `Otros Comunidad Nativa Wayampiak S/N`, `Otros Tutumberos S/N` o `Localidad De Huarca` donde no se menciona nombre de calle, etc. En estos casos se debería agregar u omitir? en caso de agregar cuál sería la etiqueta a usar?

Esa información de pueblos o barrios puede servir para generar nodos con la clave place, también se pueden dejar en la etiqueta de "addr:full". En el caso del S/N, [no se recomienda](https://josm.openstreetmap.de/ticket/17486
) poner como valor de addr:housenumber.

> Ok, con esta aclaración las etiquetas a usar serían:
> amenity=doctors; para establecimientos pequeños con ref:category=I-1.
> amenity=clinic; para establecimientos medianos con ref:category=I-3.
> amenity=hospital; para establecimientos grandes
> Es esto correcto?

Si, yo anteriormente había estado viendo que en muchos casos los que eran I-1 e I-2 solían ser establecimientos pequeños, mientras que varios de I-3 e I-4 eran medianos y varios grandes eran de II-1 para arriba.
